'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\PP4.mdb")>  _
        Public ReadOnly Property PP4ConnectionString() As String
            Get
                Return CType(Me("PP4ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ne")>  _
        Public Property AktivacijskiKljuc() As String
            Get
                Return CType(Me("AktivacijskiKljuc"),String)
            End Get
            Set
                Me("AktivacijskiKljuc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ne")>  _
        Public Property Instalacija() As String
            Get
                Return CType(Me("Instalacija"),String)
            End Get
            Set
                Me("Instalacija") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\PP4a.mdb")>  _
        Public ReadOnly Property PP4aConnectionString() As String
            Get
                Return CType(Me("PP4aConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\PP5.mdb")>  _
        Public ReadOnly Property PP5ConnectionString() As String
            Get
                Return CType(Me("PP5ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\PP5a.mdb")>  _
        Public ReadOnly Property PP5aConnectionString() As String
            Get
                Return CType(Me("PP5aConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("HRK")>  _
        Public Property Valuta() As String
            Get
                Return CType(Me("Valuta"),String)
            End Get
            Set
                Me("Valuta") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlLightLight")>  _
        Public Property DgvBoja() As Global.System.Drawing.Color
            Get
                Return CType(Me("DgvBoja"),Global.System.Drawing.Color)
            End Get
            Set
                Me("DgvBoja") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GradientActiveCaption")>  _
        Public Property DgvBojaSelect() As Global.System.Drawing.Color
            Get
                Return CType(Me("DgvBojaSelect"),Global.System.Drawing.Color)
            End Get
            Set
                Me("DgvBojaSelect") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Doručak")>  _
        Public Property Obrok1() As String
            Get
                Return CType(Me("Obrok1"),String)
            End Get
            Set
                Me("Obrok1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Jutarnja užina")>  _
        Public Property Obrok2() As String
            Get
                Return CType(Me("Obrok2"),String)
            End Get
            Set
                Me("Obrok2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ručak")>  _
        Public Property Obrok3() As String
            Get
                Return CType(Me("Obrok3"),String)
            End Get
            Set
                Me("Obrok3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Popodnevna užina")>  _
        Public Property Obrok4() As String
            Get
                Return CType(Me("Obrok4"),String)
            End Get
            Set
                Me("Obrok4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Večera")>  _
        Public Property Obrok5() As String
            Get
                Return CType(Me("Obrok5"),String)
            End Get
            Set
                Me("Obrok5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Obrok pred spavanje")>  _
        Public Property Obrok6() As String
            Get
                Return CType(Me("Obrok6"),String)
            End Get
            Set
                Me("Obrok6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("128")>  _
        Public Property PP5StartKod1() As Integer
            Get
                Return CType(Me("PP5StartKod1"),Integer)
            End Get
            Set
                Me("PP5StartKod1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("465")>  _
        Public Property PP5StartKod2() As Integer
            Get
                Return CType(Me("PP5StartKod2"),Integer)
            End Get
            Set
                Me("PP5StartKod2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("310")>  _
        Public Property PP5StartKod3() As Integer
            Get
                Return CType(Me("PP5StartKod3"),Integer)
            End Get
            Set
                Me("PP5StartKod3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("279")>  _
        Public Property PP5StartKod4() As Integer
            Get
                Return CType(Me("PP5StartKod4"),Integer)
            End Get
            Set
                Me("PP5StartKod4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ne")>  _
        Public Property PP5StartAktivacija() As String
            Get
                Return CType(Me("PP5StartAktivacija"),String)
            End Get
            Set
                Me("PP5StartAktivacija") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PP5StartAktivacijaDatum() As Date
            Get
                Return CType(Me("PP5StartAktivacijaDatum"),Date)
            End Get
            Set
                Me("PP5StartAktivacijaDatum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("214")>  _
        Public Property PP5PremiumKod1() As Integer
            Get
                Return CType(Me("PP5PremiumKod1"),Integer)
            End Get
            Set
                Me("PP5PremiumKod1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("328")>  _
        Public Property PP5PremiumKod2() As Integer
            Get
                Return CType(Me("PP5PremiumKod2"),Integer)
            End Get
            Set
                Me("PP5PremiumKod2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("316")>  _
        Public Property PP5PremiumKod3() As Integer
            Get
                Return CType(Me("PP5PremiumKod3"),Integer)
            End Get
            Set
                Me("PP5PremiumKod3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("242")>  _
        Public Property PP5PremiumKod4() As Integer
            Get
                Return CType(Me("PP5PremiumKod4"),Integer)
            End Get
            Set
                Me("PP5PremiumKod4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ne")>  _
        Public Property PP5PremiumAktivacija() As String
            Get
                Return CType(Me("PP5PremiumAktivacija"),String)
            End Get
            Set
                Me("PP5PremiumAktivacija") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PP5PremiumAktivacijaDatum() As Date
            Get
                Return CType(Me("PP5PremiumAktivacijaDatum"),Date)
            End Get
            Set
                Me("PP5PremiumAktivacijaDatum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("324-735-286-139")>  _
        Public Property PP5StartTrajnaLicencaKod() As String
            Get
                Return CType(Me("PP5StartTrajnaLicencaKod"),String)
            End Get
            Set
                Me("PP5StartTrajnaLicencaKod") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ne")>  _
        Public Property PP5StartTrajnaLicencaAktivacija() As String
            Get
                Return CType(Me("PP5StartTrajnaLicencaAktivacija"),String)
            End Get
            Set
                Me("PP5StartTrajnaLicencaAktivacija") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("486-217-423-352")>  _
        Public Property PP5PremiumTrajnaLicencaKod() As String
            Get
                Return CType(Me("PP5PremiumTrajnaLicencaKod"),String)
            End Get
            Set
                Me("PP5PremiumTrajnaLicencaKod") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ne")>  _
        Public Property PP5PremiumTrajnaLicencaAktivacija() As String
            Get
                Return CType(Me("PP5PremiumTrajnaLicencaAktivacija"),String)
            End Get
            Set
                Me("PP5PremiumTrajnaLicencaAktivacija") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("134")>  _
        Public Property PP5Premium2MjKod1() As Integer
            Get
                Return CType(Me("PP5Premium2MjKod1"),Integer)
            End Get
            Set
                Me("PP5Premium2MjKod1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("128")>  _
        Public Property PP5Premium2MjKod2() As Integer
            Get
                Return CType(Me("PP5Premium2MjKod2"),Integer)
            End Get
            Set
                Me("PP5Premium2MjKod2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("243")>  _
        Public Property PP5Premium2MjKod3() As Integer
            Get
                Return CType(Me("PP5Premium2MjKod3"),Integer)
            End Get
            Set
                Me("PP5Premium2MjKod3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("154")>  _
        Public Property PP5Premium2MjKod4() As Integer
            Get
                Return CType(Me("PP5Premium2MjKod4"),Integer)
            End Get
            Set
                Me("PP5Premium2MjKod4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ne")>  _
        Public Property PP5Premium2MjAktivacija() As String
            Get
                Return CType(Me("PP5Premium2MjAktivacija"),String)
            End Get
            Set
                Me("PP5Premium2MjAktivacija") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PP5Premium2MjAktivacijaDatum() As Date
            Get
                Return CType(Me("PP5Premium2MjAktivacijaDatum"),Date)
            End Get
            Set
                Me("PP5Premium2MjAktivacijaDatum") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ProgramPrehrane4.My.MySettings
            Get
                Return Global.ProgramPrehrane4.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
