Module BazaJelovnikaBindingClearModul
    Sub BazaJelovnikaBindingClear()
        On Error Resume Next
        With Form1
            'Baza Naziva Jelovnika
            .Label180.DataBindings.Clear()
            .Label181.DataBindings.Clear()
            .Label182.DataBindings.Clear()
            .Label183.DataBindings.Clear()
            .Label184.DataBindings.Clear()
            .Label185.DataBindings.Clear()
            .Label186.DataBindings.Clear()
            .Label187.DataBindings.Clear()

            'Baza Jelovnika
            .Label107.DataBindings.Clear()
            .Label108.DataBindings.Clear()
            .Label109.DataBindings.Clear()
            .Label110.DataBindings.Clear()
            .Label111.DataBindings.Clear()
            .Label112.DataBindings.Clear()
            .Label113.DataBindings.Clear()
            .Label114.DataBindings.Clear()
            .Label115.DataBindings.Clear()
            .Label116.DataBindings.Clear()
            .Label119.DataBindings.Clear()
            .Label120.DataBindings.Clear()
            .Label121.DataBindings.Clear()
            .Label122.DataBindings.Clear()
            .Label123.DataBindings.Clear()
            .Label124.DataBindings.Clear()
            .Label125.DataBindings.Clear()
            .Label126.DataBindings.Clear()
            .Label127.DataBindings.Clear()
            .Label128.DataBindings.Clear()
            .Label129.DataBindings.Clear()
            .Label130.DataBindings.Clear()
            .Label131.DataBindings.Clear()
            .Label132.DataBindings.Clear()
            .Label133.DataBindings.Clear()
            .Label134.DataBindings.Clear()
            .Label135.DataBindings.Clear()
            .Label136.DataBindings.Clear()
            .Label137.DataBindings.Clear()
            .Label138.DataBindings.Clear()
            .Label139.DataBindings.Clear()
            .Label140.DataBindings.Clear()
            .Label141.DataBindings.Clear()
            .Label142.DataBindings.Clear()
            .Label143.DataBindings.Clear()
            .Label144.DataBindings.Clear()
            .Label145.DataBindings.Clear()
            .Label146.DataBindings.Clear()
            .Label147.DataBindings.Clear()
            .Label148.DataBindings.Clear()
            .Label149.DataBindings.Clear()
            .Label150.DataBindings.Clear()
            .Label151.DataBindings.Clear()
            .Label152.DataBindings.Clear()
            .Label153.DataBindings.Clear()
            .Label154.DataBindings.Clear()
            .Label155.DataBindings.Clear()
            .Label156.DataBindings.Clear()
            .Label157.DataBindings.Clear()
            .Label158.DataBindings.Clear()
            .Label159.DataBindings.Clear()
            .Label160.DataBindings.Clear()
            .Label161.DataBindings.Clear()
            .Label162.DataBindings.Clear()
            .Label163.DataBindings.Clear()
            .Label164.DataBindings.Clear()
            .Label165.DataBindings.Clear()
            .Label166.DataBindings.Clear()
            .Label167.DataBindings.Clear()
            .Label168.DataBindings.Clear()
            .Label169.DataBindings.Clear()
            .Label170.DataBindings.Clear()
            .Label171.DataBindings.Clear()
            .Label172.DataBindings.Clear()
            .Label173.DataBindings.Clear()
            .Label174.DataBindings.Clear()

            'ObrokBroj, TermickaObrada, Cijena
            .Label358.DataBindings.Clear()
            .Label359.DataBindings.Clear()
            .Label360.DataBindings.Clear()

        End With
    End Sub
End Module
